# Generated by Django 4.2.5 on 2023-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screenwriting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
